services:
  012_nginx:
    build:
      context: ../../
      dockerfile: "./runtimes/012_nginx_nginx_unit/nginx/nginx.Dockerfile"
    image: 012_nginx
    container_name: "012_nginx"
    hostname: symfony7site
    ports:
      - "80:80"
    networks:
      - php-benchmarks
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1gb"
        reservations:
          cpus: "1"
          memory: "1gb"

  012_nginx_unit:
    build:
      context: ../../
      dockerfile: "./runtimes/012_nginx_nginx_unit/unit/unit.Dockerfile"
    image: 012_nginx_unit
    container_name: "012_nginx_unit"
    hostname: symfony7site
    # ports:
    #   - "80:80"
    networks:
      - php-benchmarks
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1gb"
        reservations:
          cpus: "1"
          memory: "1gb"
networks:
  php-benchmarks:
    name: php-benchmarks
